[build]
  functions = "functions"
  command = "npm run build"
  publish = "dist"

[dev]
  command = "npm run dev:vite"
  targetPort = 5173
  port = 8888
  publish = "public"
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type"
    Access-Control-Allow-Methods = "POST, OPTIONS"
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type"
    Access-Control-Allow-Methods = "POST, OPTIONS"